### ISSUE TITLE
RTMP throws fatal exception

### ISSUE THREAD

**Issue by LloydBlv** [ant-media/LibRtmp-Client-for-Android#44]
While playing RTMP stream this weird exception happens, And gives no clue about why its happening:

> E/ExoPlayerImplInternal: Source error.
                                                                 net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
                                                                     at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:53)
                                                                     at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137)
                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
08-26 22:40:08.186 7769-9587/com.aparat A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xf88e3c8c in tid 9587 (Loader:Extracto)

Please help!

**Comment by mekya** [comment]
Please check out the [RTMPIOException errorcode](https://github.com/ant-media/LibRtmp-Client-for-Android/blob/master/rtmp-client/src/main/java/net/butterflytv/rtmp_client/RtmpClient.java#L18)

Can I test the rtmp url?

**Comment by LloydBlv** [comment]
@mekya Thanks for your response, the url is generated dynamically, so I cant share, I looked at the url you mentioned, Is there anyway to prevent the app from crash and show a proper error message?

**Comment by mekya** [comment]
Yeah sure, have you tried to  catch the RTMPIOException with try-catch block and show an appropriate message?

**Comment by ojw28** [comment]
The app doesn't crash when this error occurs. It's already caught by ExoPlayer internally, and propagated to the player's event listener (which gives you a handy point where you can show an appropriate error message).

If your app is crashing, it's not directly related to the logging at the top of this thread. You'd need to provide a more complete log or bug report.

**Comment by keremkusmezer** [comment]
I have also a similar issue you can find the bug detail in 
https://github.com/google/ExoPlayer/issues/3156

Rtmp Client also dies

**Comment by mekya** [comment]
It is interesting. The thread you mentioned(https://github.com/google/ExoPlayer/issues/3156) has been resolved.  You are still having the sampe problem?

**Comment by nagendraK6** [comment]
I am testing antmedia server and getting similar exception.

**Comment by nagendraK6** [comment]
/ExoPlayerImplInternal: Source error.
                                                                                              net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
                                                                                                  at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:53)
                                                                                                  at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
                                                                                                  at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
                                                                                                  at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                  at java.lang.Thread.run(Thread.java:764)

**Comment by aktjkt** [comment]
Still Getting the same issue 
E/ExoPlayerImplInternal: Source error.
    net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Please Help

**Comment by MarkDylan100** [comment]
@mekya how can I catch the error?
private fun play(rtmpUri: String) {
        try {
            player = ExoPlayerFactory.newSimpleInstance(
                    DefaultRenderersFactory(this), DefaultTrackSelector(), DefaultLoadControl())
            val playerView = findViewById<SimpleExoPlayerView>(R.id.player_view)
//        val uri = Uri.parse(BuildConfig.STREAMING_URL)
            val uri = Uri.parse(rtmpUri)

            playerView.player = player

            val mediaSource = ExtractorMediaSource(uri, RtmpDataSourceFactory(), DefaultExtractorsFactory(), null, null)

            player?.prepare(mediaSource)
            player?.playWhenReady = true
        } catch (e: Exception) {
            println("invalid uri")
        }
    }

this code doesn't do anything

**Comment by MarkDylan100** [comment]
@mekya how can I catch the error?
`private fun play(rtmpUri: String) {
        try {
            player = ExoPlayerFactory.newSimpleInstance(
                    DefaultRenderersFactory(this), DefaultTrackSelector(), DefaultLoadControl())
            val playerView = findViewById<SimpleExoPlayerView>(R.id.player_view)
//        val uri = Uri.parse(BuildConfig.STREAMING_URL)
            val uri = Uri.parse(rtmpUri)

            playerView.player = player

            val mediaSource = ExtractorMediaSource(uri, RtmpDataSourceFactory(), DefaultExtractorsFactory(), null, null)

            player?.prepare(mediaSource)
            player?.playWhenReady = true
        } catch (e: Exception) {
            println("invalid uri")
        }
    }`

this try catch doesn't do anything

**Comment by MarkDylan100** [comment]
@mekya how cant I catch the error?

    `private fun play(rtmpUri: String) {
        try {
            player = ExoPlayerFactory.newSimpleInstance(
                    DefaultRenderersFactory(this), DefaultTrackSelector(), DefaultLoadControl())
            val playerView = findViewById<SimpleExoPlayerView>(R.id.player_view)
//        val uri = Uri.parse(BuildConfig.STREAMING_URL)
            val uri = Uri.parse(rtmpUri)

            playerView.player = player

            val mediaSource = ExtractorMediaSource(uri, RtmpDataSourceFactory(), DefaultExtractorsFactory(), null, null)

            player?.prepare(mediaSource)
            player?.playWhenReady = true
        } catch (e: Exception) {
            println("invalid uri")
        }
    }`


this code doesn't do anything
