### ISSUE TITLE
RtmpIOException with OPEN_CONNECT error

### ISSUE THREAD

**Issue by gevariya-ajit** [ant-media/LibRtmp-Client-for-Android#59]
```
E/ExoPlayerImplInternal: Source error.
net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

I have seen this error in many issues and some of them are already close but still i am not getting through.
Error is in my own app(not in demo), we are moving ffmpeg(IjkMediaPlayer) to ExoPlayer connection to stream our own camera, works fine IjkMediaPlayer but somehow not working with ExoPlayer.
### ExoPlayer Setup
>Running latest ExoPlayer 2.7.0
>Tested with diff params in URL
`rtmp://192.168.42.5:1936/live/myStream live=1 timeout=-1 buffer=32000 playpath=/myStream`

### Code
```
            player.setVideoSurface(surfaceHolder.surface)
            val factory = ExtractorMediaSource.Factory(RtmpDataSourceFactory())
            val extractorMediaSource =
                factory.createMediaSource(
                    Uri.parse("rtmp://192.168.42.5:1936/live/myStream live=1 timeout=-1 buffer=32000 playpath=/myStream"))
            player.playWhenReady = true
            player.addListener(object : Player.EventListener { ... })
            player.prepare(extractorMediaSource)
```

### Positive IjkMediaPlayer setup.
```
            player.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtmp_listen", 1)
            player.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", -1)
            player.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "rtmp_live", "live")
            player.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 32)
            player.dataSource = streamUrl
            player.setDisplay(surfaceHolder)
            player.prepareAsync()
```

**Comment by gevariya-ajit** [comment]
#44

**Comment by gevariya-ajit** [comment]
###Update
After cloning this project and debugging native `c` files, I found that the problem is with socket connection and giving `Connection refused` error with 111 code.
https://gist.github.com/gabrielfalcao/4216897

Still figuring how to fix though...

**Comment by mekya** [comment]
Are you stilll having the same issue?

May I try your stream url?

**Comment by gevariya-ajit** [comment]
Yeah, I am connecting with my camera so URL is not helpful. FFMPEG able to connect though.

**Comment by mekya** [comment]
I think you may want to use Ant Media Server which our team develops :)

https://antmedia.io

**Comment by gevariya-ajit** [comment]
Ah cool thanks 👍

**Comment by aktjkt** [comment]
Still getting the same Issue Unable to resolve please help

E/ExoPlayerImplInternal: Source error.
    net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
