### ISSUE TITLE
Error in playing RTMP Audio Stream

### ISSUE THREAD

**Issue by tspvivek** [ant-media/LibRtmp-Client-for-Android#65]
I tried playing a RTMP audio ExoPlayer, which in-turn uses LibRtmp. Could someone please help me with the issue [Error in playing RTMP Stream](https://github.com/google/ExoPlayer/issues/4200).

**Comment by tspvivek** [comment]
@mekya  Can you help me with this issue?

**Comment by ojw28** [comment]
Some additional information: This issue was originally reported trying to play `rtmp://mbcmediaserver.mbcradio.tv/bestfm/livestream`. There appears to be an issue with address resolution that also prevents VLC from playing the stream successfully, however after manually resolving it to `rtmp://202.123.27.133:1935/bestfm/livestream` VLC is able to play the stream successfully, where-as ExoPlayer is still not.

I'd suggest focusing efforts here on getting playback of `rtmp://202.123.27.133:1935/bestfm/livestream` to work. I think the failure occurs somewhere in `RTMP_Connect`. @mekya - Would it be possible for you to attempt to root cause what's going on?

**Comment by woehrl** [comment]
What's the status of this bug? I'm still experiencing the same results using ExoPlayer 2.9.4 with librtmp 3.0.1 and a nginx/rtmp source.

 ```
E/ExoPlayerImplInternal: Source error.
    net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:60)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:886)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```
