### ISSUE TITLE
RtmpClient$RtmpIOException 

### ISSUE THREAD

**Issue by aktjkt** [ant-media/LibRtmp-Client-for-Android#66]
when trying to play rtmp url using exo player getting following issue 

E/ExoPlayerImplInternal: Source error.
    net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

I am using following dependencies

implementation 'com.google.android.exoplayer:exoplayer:2.7.3'
implementation 'com.google.android.exoplayer:extension-rtmp:2.7.3'

**Comment by ojw28** [comment]
This should be marked a duplicate of https://github.com/ant-media/LibRtmp-Client-for-Android/issues/65
